/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as ConversationRouteImport } from './routes/conversation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecorderRouteImport } from './routes/recorder'
import { Route as SpeechToSpeechRouteImport } from './routes/speech-to-speech'
import { Route as SpeechToTextRouteImport } from './routes/speech-to-text'
import { Route as ApiAuthConfigRouteImport } from './routes/api/auth-config'
import { Route as ApiGetEphemeralTokenRouteImport } from './routes/api/get-ephemeral-token'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as HistoryTimestampRouteImport } from './routes/history/$timestamp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationRoute = ConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecorderRoute = RecorderRouteImport.update({
  id: '/recorder',
  path: '/recorder',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechToSpeechRoute = SpeechToSpeechRouteImport.update({
  id: '/speech-to-speech',
  path: '/speech-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechToTextRoute = SpeechToTextRouteImport.update({
  id: '/speech-to-text',
  path: '/speech-to-text',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthConfigRoute = ApiAuthConfigRouteImport.update({
  id: '/api/auth-config',
  path: '/api/auth-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetEphemeralTokenRoute = ApiGetEphemeralTokenRouteImport.update({
  id: '/api/get-ephemeral-token',
  path: '/api/get-ephemeral-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryTimestampRoute = HistoryTimestampRouteImport.update({
  id: '/history/$timestamp',
  path: '/history/$timestamp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/conversation': typeof ConversationRoute
  '/login': typeof LoginRoute
  '/recorder': typeof RecorderRoute
  '/speech-to-speech': typeof SpeechToSpeechRoute
  '/speech-to-text': typeof SpeechToTextRoute
  '/api/auth-config': typeof ApiAuthConfigRoute
  '/api/get-ephemeral-token': typeof ApiGetEphemeralTokenRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/history/$timestamp': typeof HistoryTimestampRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/conversation': typeof ConversationRoute
  '/login': typeof LoginRoute
  '/recorder': typeof RecorderRoute
  '/speech-to-speech': typeof SpeechToSpeechRoute
  '/speech-to-text': typeof SpeechToTextRoute
  '/api/auth-config': typeof ApiAuthConfigRoute
  '/api/get-ephemeral-token': typeof ApiGetEphemeralTokenRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/history/$timestamp': typeof HistoryTimestampRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/conversation': typeof ConversationRoute
  '/login': typeof LoginRoute
  '/recorder': typeof RecorderRoute
  '/speech-to-speech': typeof SpeechToSpeechRoute
  '/speech-to-text': typeof SpeechToTextRoute
  '/api/auth-config': typeof ApiAuthConfigRoute
  '/api/get-ephemeral-token': typeof ApiGetEphemeralTokenRoute
  '/api/session': typeof ApiSessionRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/history/$timestamp': typeof HistoryTimestampRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-callback'
    | '/conversation'
    | '/login'
    | '/recorder'
    | '/speech-to-speech'
    | '/speech-to-text'
    | '/api/auth-config'
    | '/api/get-ephemeral-token'
    | '/api/session'
    | '/auth/logout'
    | '/history/$timestamp'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-callback'
    | '/conversation'
    | '/login'
    | '/recorder'
    | '/speech-to-speech'
    | '/speech-to-text'
    | '/api/auth-config'
    | '/api/get-ephemeral-token'
    | '/api/session'
    | '/auth/logout'
    | '/history/$timestamp'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/auth-callback'
    | '/conversation'
    | '/login'
    | '/recorder'
    | '/speech-to-speech'
    | '/speech-to-text'
    | '/api/auth-config'
    | '/api/get-ephemeral-token'
    | '/api/session'
    | '/auth/logout'
    | '/history/$timestamp'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ConversationRoute: typeof ConversationRoute
  LoginRoute: typeof LoginRoute
  RecorderRoute: typeof RecorderRoute
  SpeechToSpeechRoute: typeof SpeechToSpeechRoute
  SpeechToTextRoute: typeof SpeechToTextRoute
  ApiAuthConfigRoute: typeof ApiAuthConfigRoute
  ApiGetEphemeralTokenRoute: typeof ApiGetEphemeralTokenRoute
  ApiSessionRoute: typeof ApiSessionRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  HistoryTimestampRoute: typeof HistoryTimestampRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation': {
      id: '/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorder': {
      id: '/recorder'
      path: '/recorder'
      fullPath: '/recorder'
      preLoaderRoute: typeof RecorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech-to-speech': {
      id: '/speech-to-speech'
      path: '/speech-to-speech'
      fullPath: '/speech-to-speech'
      preLoaderRoute: typeof SpeechToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech-to-text': {
      id: '/speech-to-text'
      path: '/speech-to-text'
      fullPath: '/speech-to-text'
      preLoaderRoute: typeof SpeechToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-config': {
      id: '/api/auth-config'
      path: '/api/auth-config'
      fullPath: '/api/auth-config'
      preLoaderRoute: typeof ApiAuthConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-ephemeral-token': {
      id: '/api/get-ephemeral-token'
      path: '/api/get-ephemeral-token'
      fullPath: '/api/get-ephemeral-token'
      preLoaderRoute: typeof ApiGetEphemeralTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$timestamp': {
      id: '/history/$timestamp'
      path: '/history/$timestamp'
      fullPath: '/history/$timestamp'
      preLoaderRoute: typeof HistoryTimestampRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ConversationRoute: ConversationRoute,
  LoginRoute: LoginRoute,
  RecorderRoute: RecorderRoute,
  SpeechToSpeechRoute: SpeechToSpeechRoute,
  SpeechToTextRoute: SpeechToTextRoute,
  ApiAuthConfigRoute: ApiAuthConfigRoute,
  ApiGetEphemeralTokenRoute: ApiGetEphemeralTokenRoute,
  ApiSessionRoute: ApiSessionRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  HistoryTimestampRoute: HistoryTimestampRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
